name: cholinesterase-qsar
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - rdkit
  - lightgbm
  - joblib
  - pip
  - pip:
      - xgboost
      - catboost
